# aws s3
development:
  bucket: juguetea_dev
  access_key_id: AKIAIRX6KHPYH54MPSGQ
  secret_access_key: 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
test:
  bucket: juguetea_test
  access_key_id: AKIAIRX6KHPYH54MPSGQ
  secret_access_key: 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
production:
  bucket: juguetea_prod
  access_key_id: AKIAIRX6KHPYH54MPSGQ
  secret_access_key: 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