# aws s3
common: &common
  access_key_id: AKIAIRX6KHPYH54MPSGQ
  secret_access_key: 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
  
development:
  <<: *common
  bucket: juguetea.dev

test:
  <<: *common
  bucket: juguetea.test

production:
  <<: *common
  bucket: juguetea.prod